# Generated by Django 4.0.6 on 2023-05-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DialogueBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=250)),
                ('rating', models.IntegerField(default=0)),
                ('agree', models.BooleanField(default=False)),
            ],
        ),
    ]
